train_mode: "all_train2018_sup"
val_mode: "test2019_new"
test_mode: "only_test2018"
n_epochs: 50
lr: 0.001
scheduler_step_size: 5
batch_size: 32
lr_gamma: 0.3
t1: True
t2: True
t1ce: True
augment: True
wmh_threshold: 0.5
optimizer: "SGD" #SGD OR ADAM
mixup_threshold: None
intensity_rescale: True
oneHot: False
experiment_mode: "semi"
parallel: True
train_unsup_mode: "train2018_semi_unsup"
train_sup_mode: "train2018_semi_sup"
train_sup_rate: 10
cuda: "0,1"
seed: 41
loss: 'CE' # CE, DSC, FOCAL, CE_DSC, CE_FOCAL, DSC_FOCAL, CE_FOCAL_DSC
semi_mode: "shared"   # shared, MT
gradient_stop_strategy: "stop_feature" #stop_feature, stop_output
information_passing_strategy: "teacher" #student, teacher
information: "semi supervised, pass teacher's features, MT, supervised: student, stop gradietn: teacher "  # description
model: "PGS" #PGS,PGSMT, UNET